### ISSUE TITLE
Request support for overriding an existing tag, release, defaults to FALSE .

### ISSUE THREAD

**Issue by fscarmen** [shogo82148/actions-create-release#1074]
![image](https://github.com/shogo82148/actions-create-release/assets/62703343/87a3a966-b66e-4af0-875c-a6cf65be9ba1)

**Comment by shogo82148** [comment]
It is recommended to give a unique name to the release. Do you still need an override option?

**Comment by shogo82148** [comment]
for example:

- https://github.com/reviewdog/nightly/releases/tag/v0.16.0-nightly20240111%2Bf00ee4a
- https://github.com/kayac/ecspresso/releases/tag/v2.3.1-nightly-c780f9f3672d7c0fced8eed43cc66a573611d848

**Comment by fscarmen** [comment]
Yes, I would still like to add that option. Because the same release has updated packages, right now we can only remove the tag and release manually before running workflows, or we can use another project to remove it, like https://github.com/dev-drprasad/delete-tag-and-release.
Adding overwrite option to this project would be very convenient for development and debugging.

**Comment by shogo82148** [comment]
https://github.com/shogo82148/actions-create-release/pull/1076 implements the overwrite option.

**Comment by shogo82148** [comment]
released https://github.com/shogo82148/actions-create-release/releases/tag/v1.6.0

**Comment by fscarmen** [comment]
It work. Thank you!
